/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package prog2.vista;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Hashtable;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import prog2.adaptador.Adaptador;

/**
 *
 * @author Usuario
 */
public class gestio_elements_finestra extends javax.swing.JDialog {

    /**
     * Creates new form Gestió_elements_finestra
     */
    Adaptador adaptador;
    AppCentralUB parent;
    public gestio_elements_finestra(java.awt.Frame parent_, boolean modal, Adaptador adaptador, AppCentralUB parent) {
        super(parent_, modal);
        this.parent = parent;
        this.adaptador = adaptador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton2 = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Reactor");
        String imagePath = adaptador.getActivitatReactor() ? "/imatges/ON.png" : "/imatges/OFF.png";
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        jToggleButton1.setIcon(icon);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 150, 60));

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 460, 20));
        jSlider1.setMinimum(0);
        jSlider1.setMaximum(100);
        int valor = (int) adaptador.getBarres();
        jSlider1.setValue(valor);
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMinorTickSpacing(1);

        // Create a label table for custom labels
        Hashtable<Integer, JLabel> labelTable = new Hashtable<>();
        labelTable.put(0, new JLabel("0"));
        labelTable.put(20, new JLabel("20"));
        labelTable.put(40, new JLabel("40"));
        labelTable.put(60, new JLabel("60"));
        labelTable.put(80, new JLabel("80"));
        labelTable.put(100, new JLabel("100"));
        jSlider1.setLabelTable(labelTable);

        // Configure the JLabel
        jLabel2.setText("Value: " + adaptador.getBarres());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Barres inserides: " + (int) adaptador.getBarres());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 280, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 250, 40));
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addAll(adaptador.getBombesString());
        jComboBox1.setModel(model);

        jToggleButton2.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("Selecciona una bomba refrigerant");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 250, 40));

        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 550, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/no_tocar.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, 130));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tancar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 680, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/fondo_elementos.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1080, -140, 1880, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            if(adaptador.getActivitatReactor()){
                adaptador.opcio2_2();
            }
            else{
                adaptador.opcio2_1();
            }
            setButtonImages();
        }
        catch(CentralUBException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error: ", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        int value = jSlider1.getValue();
        jLabel2.setText("Barres inserides: " + value);
        parent.actualitzaBarra(value);
       
        try{
            adaptador.opcio1_2(value);
        }
        catch(CentralUBException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error: ", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_jSlider1StateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        boolean estat = true;
        try{
            estat = adaptador.getEstatID(jComboBox1.getSelectedIndex());
            adaptador.setEstatID(jComboBox1.getSelectedIndex(), estat);
        }
        catch(CentralUBException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error: ", JOptionPane.ERROR_MESSAGE); 
        }
        setButtonImages2(estat);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        boolean estat = true;
        try{
            estat = !adaptador.getEstatID(jComboBox1.getSelectedIndex());
            adaptador.setEstatID(jComboBox1.getSelectedIndex(), estat);
        }
        catch(CentralUBException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error: ", JOptionPane.ERROR_MESSAGE); 
        }
        setButtonImages2(estat);
        actualitzaComboBox();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        showLoadingDialog();
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void showLoadingDialog() {
        JDialog loadingDialog = new JDialog(this, true);
        loadingDialog.setUndecorated(true);
        loadingDialog.setLayout(new BorderLayout());

        JLabel gifLabel = new JLabel(new ImageIcon(getClass().getResource("/imatges/explosion2.gif")));
        loadingDialog.add(gifLabel, BorderLayout.CENTER);

        loadingDialog.pack();
        loadingDialog.setLocationRelativeTo(this);

        // Usar un Timer para cerrar el diálogo después de 3 segundos
        Timer timer = new Timer(1900, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadingDialog.dispose();
            }
        });
        timer.setRepeats(false);
        timer.start();

        // Reproducir el audio
        playSound("/imatges/sound2.wav");

        loadingDialog.setVisible(true);
    }
    
    private void playSound(String soundFilePath) {
        try {
            // Obtener el archivo de audio como un recurso
            File soundFile = new File(getClass().getResource(soundFilePath).getFile());
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(soundFile);
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }
    
    private void setButtonImages() {
        String imagePath = adaptador.getActivitatReactor() ? "/imatges/ON.png" : "/imatges/OFF.png";
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        jToggleButton1.setIcon(icon);
    }
    
    private void setButtonImages2(boolean estat){
        jToggleButton2.setText("Bomba amb ID: " + jComboBox1.getSelectedIndex());
        String imagePath2 = "";
       
        imagePath2 = estat ? "/imatges/ON.png" : "/imatges/OFF.png";
        
        ImageIcon icon2 = new ImageIcon(getClass().getResource(imagePath2));
        jToggleButton2.setIcon(icon2);
    }
    
    private void actualitzaComboBox(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addAll(adaptador.getBombesString());
        jComboBox1.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
